### ISSUE TITLE
Server Abstürze durch Wireless Crafting Terminal

### ISSUE THREAD

**Issue by c0nfirm** [StormcodersDE/Minecraft-Time#10]
Ich weiß nicht genau wie der Bug entsteht aber seit heute passiert es mir öfter dass wenn ich des Wireless Crafting Terminal benutze mein minecraft server sich neu startet und beim wiederbestritt des Spiel dann Das wireless crafting terminal aus meinem inventar entfert wurde

**Comment by lays24mc** [comment]
Gibt es einer crashlog vom Server. Das würde sehr helfen. So ist mir der Fehler bisher nicht bekannt bzw. beim Testen jetzt auch nichts aufgefallen

**Comment by c0nfirm** [comment]
[crash-2018-10-20_17.47.28-server.txt](https://github.com/StormcodersDE/Minecraft-Time/files/2501558/crash-2018-10-20_17.47.28-server.txt)
[crash-2018-10-20_18.38.52-server.txt](https://github.com/StormcodersDE/Minecraft-Time/files/2501559/crash-2018-10-20_18.38.52-server.txt)

Des müssten die crash reports mit dem Wireless Crafting terminal sein, da des die einzigen sind die ich für den tag wo ich diesen report geschrieben habe besitze.

Hab mich auch wieder erinnert wie der fehler aufgereten ist:

Ich wollte gerade die 64k crafting storages für mein autocrafting aus dem me-system holen und jedes mal als ich in's wireless therminal 64 eingegeben habe is mein spiel gecrashed

**Comment by lays24mc** [comment]
Ich habe mich einmal erkundigt. Der Bug war bekannt und wurde gefixt. Mit dem nächsten Time Update ist der Fehler dann behoben :)
