### ISSUE TITLE
Spiel Crasht nach wenigen sekunden ab 

### ISSUE THREAD

**Issue by convel** [StormcodersDE/Minecraft-Time#11]
Guten tag das spiel Stürzt nach wenigen Sekunden
 ab auf der Singelplayer world und auf den Server da ich auf den Server mit anderen Spiele weiß ich leider nicht was sie als letztes gecraftet haben aber hier ist der crash report 

[crash-2018-11-13_16.34.27-server.txt](https://github.com/StormcodersDE/Minecraft-Time/files/2576947/crash-2018-11-13_16.34.27-server.txt)

**Comment by lays24mc** [comment]
Guten Tag,

Eine FuzzyCard in einem ExportBus von Applied Energistics löst den Fehler aus. Wenn möglich diesen bitte abbauen oder abbauen lassen. Location ist: dimension=0, x=-1121, y=48, z=985

**Comment by convel** [comment]
Guten tag,
hat wunderbar funktioniert kann ohne Probleme weiter spielen vielen dank.
