### ISSUE TITLE
Quantum Ring 

### ISSUE THREAD

**Issue by Zibatown** [StormcodersDE/Minecraft-Time#19]
Hallo,

Das Problem ist wenn ich denn Server neustarte muss ich denn Quantum ring neu verbinden also ME kabel ab und dann wieder ran dann funktioniert er wieder und das immer wenn der Server Neustartet 

 - OS: [Windows]
 - Java-Version: [z.B. 7, 8, 9 etc.]
 - Modpack-Minecraft-Time [Version 1.0 ]

**Comment by Katzen48** [comment]
Bitte mal schauen, ob der Chunk auch geladen ist.
