### ISSUE TITLE
JEI-Crash ???

### ISSUE THREAD

**Issue by Keldooran** [StormcodersDE/Minecraft-Time#26]
Hello all.

I updated MC Time today from 1.2 to 1.3 via Twitch. Now, when I load my World from 1.2, then MC crash when I open the inventory or a chest or the workbench.
I downgrade the installation to 1.2 and all is normal.
Error: java.lang.ArrayIndexOutOfBoundsException: -1

 - Hardware: Intel I7-8700, GTX1080(8GB), 16GB RAM, 120GB NVRAM(System), 2x 500GB SSD(Raid 1)(Games&Programs), 2TB HD(Data), UltraWideScreen-Monitor 3840x1080 144Hz
 - OS: Win10 x64
 - Java-Version: tested with 
                                           1.8.0_51(x64) 
                                           1.8.0_231(x64)
 - Java-MEM: tested with
                                        XMX=12286M/8192M
                                        XMS=512M/256M
 - Modpack-Version 1.3

**Weitere Angaben**
[crash-2019-10-30_00.00.48-client.txt](https://github.com/StormcodersDE/Minecraft-Time/files/3786157/crash-2019-10-30_00.00.48-client.txt)

thx for your work

Update:

today v1.2 crashed by same events with the same error, like open inventory, open workbench or open a chest. I tested this on many things, but when i rightklick on a machine or other(cokeoven,  SMeltery from TinkersConstruct) then MC crash.

[crash-2019-10-30_13.34.20-client.open_wb.txt](https://github.com/StormcodersDE/Minecraft-Time/files/3788986/crash-2019-10-30_13.34.20-client.open_wb.txt)
[crash-2019-10-30_13.45.22-client.open_inventory.txt](https://github.com/StormcodersDE/Minecraft-Time/files/3788987/crash-2019-10-30_13.45.22-client.open_inventory.txt)
[crash-2019-10-30_13.56.06-client.open_cokeoven(ImmersiveEngineering).txt](https://github.com/StormcodersDE/Minecraft-Time/files/3788988/crash-2019-10-30_13.56.06-client.open_cokeoven.ImmersiveEngineering.txt)

**Comment by lays24mc** [comment]
Hi,

I apologize for the late answer. This error often occurs in connection with Optifine. I see that you have installed this on your computer. Deactivate Optifine or download the latest version of Optifine and check if it occurs again :)
