### ISSUE TITLE
EnderIO übersetztung funktioniert nicht

### ISSUE THREAD

**Issue by xXDarkNovaXx** [StormcodersDE/Minecraft-Time#27]
Ich melde mich mit dem Problem hier da bei EnderIO wenn man ein Report erstellt steht wenn man ein Modpack nutzt soll man sich erst hier melden

Kann es sein das irgendwie  die Übersetztung von EnderIO nicht übernommen wird wenn man das Spiel auf Deutsch stellt
Soweit ich aus meinem 1.7.10 Modpack weiß besitzt EnderIO eine Deutsche Übersetzung aber es bleibt trotzdem English
Hab auch schon EnderIO geupdatet da ich das so oder so musste weil ich ein paar Mods hinzugefügt hatte und es dafür eh updaten musste aber wenn ich es recht in Erinnerung hab bin mir nicht mehr 100%Sicher ist zu lange her war das auch schon so als ich rein Time blank hatte ohne etwas hinzugefügt

**Comment by lays24mc** [comment]
Jede Mod hat sein eigene eigenen language Dateien. Sollte bei EnderIO eine deutsche Übersetzung in 1.12 dabei sein, wird die auch, wenn nicht modseitig fehlerhaft, geladen. Wende dich in dem Fall bitte an EnderIO :). Ich werde es dennoch bei mir einmal überprüfen

**Comment by xXDarkNovaXx** [comment]
Kann es vllt auch sein das sie entfernt wurde?
ich hab jetzt mal die Mod einfach komplett auseinander genommen und die Übersetzungen wurden entfernt so wie es aussieht WTF
ich kannte vorher nur die 1.7.10 wo sie da war
Natoll hätte ich die Daten auseinander genommen hätte ich mir das hier sparen können 
Kann man ja nicht wissen vorher

Aber EnderIO hat Project Intelligence integriert von Brandon 3055 darüber könnte man ja eine neue Übersetztung machen dafür ist es ja da werden ja über ein Server abgerufen
Immer diese extra Arbeit

**Comment by lays24mc** [comment]
Hallo,

wenn kann nur EnderIO diese entfernt haben. Wenn das der Fall ist, kann natürlich nichts auf deutsch übersetzt werden. In dem Fall eibfach EnderIO mal anschreiben und fragen ob dort die deutsche Sprache nachgereicht werden kann.
