### ISSUE TITLE
The game crashes when starting

### ISSUE THREAD

**Issue by Entropyus** [StormcodersDE/Minecraft-Time#28]
The crashreport just says that tere is an unexpectet file, that cant be downloaded

Crash report:

Eine Datei konnte nicht heruntergeladen werden; der Dateiinhalt unterscheidet sich von dem, der erwartet wurde.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Dateiname: jna-4.4.0.jar
Pfad: C:\Users\Niklas\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Existiert: File

-using win7
-never used the modpack

**Comment by lays24mc** [comment]
This is a Twitch App / Minecraft Launcher error! I can nothing do for this
