### ISSUE TITLE
Fehler im JEI

### ISSUE THREAD

**Issue by LOWFIVE89** [StormcodersDE/Minecraft-Time#30]
Ich habe heute seit einiger Zeit wieder das Mod pack installiert und musste feststellen das auf einmal im JEI in einem Crafting Interface von AE2 das Move Items geht obwohl die benötigten Items nicht im System sind.

In einer Workbench wird es angezeigt...

[Bild fast leeres System](https://www.bilder-upload.eu/bild-19530a-1595171884.png.html)

[Bild im Crafting Interface](https://www.bilder-upload.eu/bild-690990-1595171928.png.html)

[Bild Workbench](https://www.bilder-upload.eu/bild-690990-1595171928.png.html)

ist das ein Problem das jeder hat oder nur ich?

Mit freundlichen grüßen

**Comment by lays24mc** [comment]
Hallo,

das ist mittlerweile möglich. Sobald du auf das "+" drückst werden die Items dann aber nicht ins Tabler gelegt, da nicht vorhanden. Das wurde eingefügt, damit im Pattern Terminal die Rezepte fürs Autocrafting angelegt werden kann, ohne die Items schon zu besitzen.

**Comment by LOWFIVE89** [comment]
Hallo,
Du meinst im jei. Also würde das mit einer älteren Version vom jei bzw. Ae2 wieder ohne Probleme möglich sein die Anzeige "missing item " zu bekommen?

**Comment by lays24mc** [comment]
Hallo, 

dazu müsstest du, soweit ich es in Erinnerung habe, downgraden
