### ISSUE TITLE
Absturz beim Laden der Chunks/Teile der Welt

### ISSUE THREAD

**Issue by monstaa450** [StormcodersDE/Minecraft-Time#31]
**Beschreibe den Bug**
Zum beispiel gibts ein Mech Boot, wen ich in seine nähe komme stürzt es ab. Hab nen neue Welt gemacht und beim rum laufen noch ein punkt gefunden wo es die ganze zeit abstürzt.
Diesesmal kann ich aber nicht genau bestimmen ob es wieder an ein Konstrukt oder sonstiges zutun hat.

**Desktop (bitte vervollständige diese Informationen):**
 - OS: Windows
 - Java-Version:
 - Modpack-Version Neueste

**Weitere Angaben**
Hänge weitere Informationen an, welche uns helfen, das Problem zu beseitigen.

EDITED: Crashlog nach Hastebin verschoben (https://hastebin.com/yepalasoqa.rb)

**Comment by lays24mc** [comment]
Bitte einmal Optifine entfernen und dann noch einmal testen. Laut Crashlog gibt es Komplikationen zwischen TechGuns und Optifine

**Comment by monstaa450** [comment]
Ja lag anscheinend am Shader, ausgeschaltet läufts. Danke sehr
