### ISSUE TITLE
Loading - Initializing mods Phase 1

### ISSUE THREAD

**Issue by Leulmann** [StormcodersDE/Minecraft-Time#32]
**Beschreibe den Bug**
Beim Starten von Minecraft Time hängt sich die Anwendung auf, sobald sie am Punkt "Loading - Inintializing mods Phase 1 / Loading Resources 0/163" ankommt. Von hier an passiert nichts mehr.

**Wie man den Bug reproduzieren kann**
Schritte:
1. Minecraft Time im Twitch Launcher öffnen.
2. Zur Verfügung stehender Ram im Minecraft Launcher auf 12338m stellen.
3. Speichern
4. Minecraft Time starten.
5. Fehler Taucht beim 2. von den 7 Schritten auf.

**Erwartetes Verhalten**
Das Spiel sollte eigentlich starten und mir das Startmenü anzeigen.

**Screenshots**
![image](https://user-images.githubusercontent.com/68563222/87976107-d726ba00-cacc-11ea-9fb9-65c79dd039ed.png)

**Desktop (bitte vervollständige diese Informationen):**
 - OS: Windows 10
 - Java-Version: Fehler taucht sowohl ohne Java zu installieren, als auch mit Java 8 auf
 - Modpack-Version: 1.3
[latest.log](https://github.com/StormcodersDE/Minecraft-Time/files/4949605/latest.log)

**Weitere Angaben**
latest.log anbei.
[latest.log](https://github.com/StormcodersDE/Minecraft-Time/files/4949610/latest.log)

**Comment by Leulmann** [comment]
Minecraft Time wurde zuvor frisch installiert.

**Comment by lays24mc** [comment]
Bitte prüfe einmal in deinem Twitch Launcher, ob hier für Minecraft "Onedrive" als speicherort hinterlegt wurde. Wenn ja, den Pfad bitte ändern! Ansonsten sehe ich in der Log keine Auffälligkeit, welche den Fehler auslösen könnte.
