### ISSUE TITLE
Cryo Stabilized Fluxduct Anzeigefehler

### ISSUE THREAD

**Issue by GesturesKing** [StormcodersDE/Minecraft-Time#5]
Hallo zusammen,

Mir ist beim bauen in meiner eigenen Welt aufgefallen, dass bei den Cryo Stabilized Fluxducts ein kleiner Anzeige Fehler im Fenster ist. Es wird angezeigt, dass diese kein Storm haben. Diese leiten zu dem Zeitpunkt aber Strom.
Wie genau man diese Problem beheben kann, weiss ich selber nicht.^^ 
Bei mir ist alles aktuell. Von Modpack bis hin zu Java und Windows 10.

Mit freundlichen Grüßen
GesturesKing
![2018-08-24_19 59 29](https://user-images.githubusercontent.com/42680659/44600012-4bb92700-a7d8-11e8-8e8f-d17a61f91812.png)
![2018-08-24_19 59 38](https://user-images.githubusercontent.com/42680659/44600013-4bb92700-a7d8-11e8-80b0-fdb897d76f6b.png)

**Comment by GesturesKing** [comment]
Beim ersten Bild ist die rote Leiste rechts in der Garden Cloche die Energie Leiste. Beim zweiten Bild ist dieses kleine Fenster oben links gemeint. :)

**Comment by lays24mc** [comment]
Die Anzeige ist absichtlich nicht vorhanden, da das Kabel keine RF speichert, wie die anderen Duct's
