### ISSUE TITLE
Das Aufrufen der Rezepte für Glowstone führt zu einem Clientcrash

### ISSUE THREAD

**Issue by Tomcatchriss** [StormcodersDE/Minecraft-Time#6]
Wenn man Glowstone im Inventar hat, das Inventar öffnet und mit der Maus sich auf Glowstone befindet und dann 'u' drückt, crasht der Client. Dies tritt sowohl im Signleplayer, als auch im Multiplayer auf.

Modpack-Version ist 0.93b. Anbei das Crashlog. [https://hastebin.com/raw/idupirisig](url)

**Comment by lays24mc** [comment]
Crashlog führt zu einer leeren Seite. Bitte über Pastebin hochladen.

**Comment by Tomcatchriss** [comment]
https://pastebin.com/j1CNUpAn

Bitteschön :-)

**Comment by lays24mc** [comment]
Bitte entweder eigenständig auf die neue JEI Version updaten oder auf ein Update von Time warten :). Der Fehler sollte damit behoben sein. Das Problem mit "u" ist leider nicht nur bei Glowstone vorhanden,
