### ISSUE TITLE
Advaced Roketry Broken

### ISSUE THREAD

**Issue by c0nfirm** [StormcodersDE/Minecraft-Time#7]
Gestern hat mein server es plötzlich nicht mehr geschafft sich zu starten (Gportal server)

Laut support ist die dateil /OGC/advRocketry/planetDefs.xml broken und ich soll versuchen die mod/datei zu entfernen...

Hier ist mein aktuellster crash report
https://pastebin.com/wMABKNym

**Comment by lays24mc** [comment]
Aus dem Crash Report kann ich leider nicht erkennen, dass es an AR liegt. Sollte der Support von Gportal aber recht haben, entferne in deinem Save Ordner bzw. in deinem world-Ordner den Ordner advRocketry. Dieser wird beim Serverneustart neu angelegt. **Achtung**: Alle Planeten werden in dem Fall resettet.

**Comment by c0nfirm** [comment]
Jaaa, es hat in meinem fall gereicht die eine datei zu entfernen ^^
