### ISSUE TITLE
Quantum Quarry

### ISSUE THREAD

**Issue by TroLLzOr97** [StormcodersDE/Minecraft-Time#8]
I have the problem, that the QQ is ignoring the Biome Markers, so that you can't mine in the Nether or the End with the QQ.

**Comment by lays24mc** [comment]
Nether and Biom Marker ( and in Nether/End) are disabled duo bug. When you need this, activate it in the extrautilities2.cfg

**Comment by TroLLzOr97** [comment]
Could you please explain to me how to do this?

**Comment by lays24mc** [comment]
Go to config file. Than open the extrautillities.cfg. 

`B:"Quantum Quarry: Enable Nether/End biome generation (has been buggy)"=false`

Edit this to "true". Restart server and have fun :)

The QQ in Nether oder END DIM is disable from the modder self.

**Comment by TroLLzOr97** [comment]
Thank you very much it is working :)
