### ISSUE TITLE
Rezept-Bug: Resonant Redstone Crystal

### ISSUE THREAD

**Issue by gitErich** [StormcodersDE/Minecraft-Time#9]
**Beschreibe den Bug**

Mit 1x RedstoneOre und 1x Petrotheum Dust sollten 2x Resonant Redstone Crystals gecrafted werden können. Es ergibt aber derzeit 2x Restone 

**Erwartetes Verhalten**

1x RedstoneOre und 1x Petrotheum Dust sollte 2x Resonant Redstone Crystal ergeben.

**Screenshots**

**Erwartet:**
![ist](https://user-images.githubusercontent.com/33221424/46756989-1e153800-ccc9-11e8-8ad3-b1a847aa7bc9.PNG)

**Ist:**
![erwartetsergebnis](https://user-images.githubusercontent.com/33221424/46756992-20779200-ccc9-11e8-8b4e-475812fef860.PNG)

**Desktop (bitte vervollständige diese Informationen):**
 - OS: Windows
 - Java-Version: 1.8
 - Modpack-Version 0.94

**Weitere Angaben**
/

**Comment by lays24mc** [comment]
Entschuldige die späte Antwort. War leider wegen Erkältung ans Bett gefesselt. Der Fehler wird mit dem nächsten Update von Time behoben :)

**Comment by gitErich** [comment]
Alles klar, cool. Danke für die Info und erhol dich noch gut :)
